### ISSUE TITLE
Feature Request: show name of token in popup

### ISSUE THREAD

**Issue by itamarcu** [schlosrat/token-health#19]
Often, my group's GMs select the wrong token before dealing damage or healing.

It would be really helpful if the Token Health popup included the name of the token/actor being healed.  It would be even more useful if it had the token's image somewhere.

**Comment by itamarcu** [comment]
I [implemented this myself in a fork of the repository](https://github.com/itamarcu/foundry-token-health). I might clean up the commits and make it a settings option, to make a pull request.

**Comment by schlosrat** [comment]
Hi itamarcu, tonifisler has kindly agreed to allow me to take on this mod. I've implemented a fix for an issue and added a couple of features I and others playing the AGE system wanted. I'd very much like to fold in your contribution for this feature too! I'll send you an invite to collaborate on my fork of this if you like. https://github.com/schlosrat/foundry-token-health

**Comment by schlosrat** [comment]
Features added - Thanks itamarcu!
