### ISSUE TITLE
Spacebar and Delete not working.

### ISSUE THREAD

**Issue by Ax0z** [schlosrat/token-health#20]
I installed Token Health via the foundryvtt in app add-on installer, and when I activate it I cannot use the spacebar or the delete key within the game window, I can still type if I hit the text box. Not sure if this is happening to others or if there was a fix for it.

**Comment by schlosrat** [comment]
Hi, I've taken over maintenance and development of this module from the original developer. Please download and try out Version 0.3.0 and see if this issue is still present. If it is, please open a new issue for the current version.
