### ISSUE TITLE
"Configure settings" button do not work when module is active

### ISSUE THREAD

**Issue by Xam-insight** [schlosrat/token-health#21]
In the FoundryVTT Game Settings, the "Configure settings" button do not work when foundry-token-health module is active.

![image](https://user-images.githubusercontent.com/54999230/102468015-47704200-4051-11eb-883c-78b88d772b0e.png)

**Comment by schlosrat** [comment]
Please update to 0.3.0 and try again. It looks like it works correctly at my end, but maybe there's something else going on. If this persists after updating to 0.3.0 then please open a new issue.
