### ISSUE TITLE
Token moves

### ISSUE THREAD

**Issue by HippyCraig** [schlosrat/token-health#23]
When I apply damage or heal the token it moves the token on the map one square to the right for some reason.  This happens as soon as the dialog appears.  It appears that if you set D for damage, it doesn't over ride the movement function of the D key.

**Comment by schlosrat** [comment]
Correct. The module doesn't override any other keybindings, so if you happen to have D set both for this module and as a movement key, then both may get done. You may be able to find some other keybinding that will work better for you, but you'll need to make sure you're not double booking that binding or multiple things will likely happen as you've observed.
