### ISSUE TITLE
Compatibility Request DCC

### ISSUE THREAD

**Issue by justinthejaguar** [schlosrat/token-health#29]
Can you please add compatibility with the Dungeon Crawl Classics roleplaying system?

**Comment by schlosrat** [comment]
I'm not familiar with that system but if you can tell me what it is that you'd like the tool to do when the game system is set to DCC I'll be happy to look into the feasibility of those requests - and if feasible implement them such that they're only in effect for that game system and don't break things for other systems. Please reply to this thread with a description of what it is you'd like the module to do differently when the game system is DCC.

**Comment by justinthejaguar** [comment]
Actually, it appears that in the last update it began to work for DCC. Thank you.
