### ISSUE TITLE
Token Chat Capability - Please allow option to disable

### ISSUE THREAD

**Issue by Tyaeth** [schlosrat/token-health#33]
The new token chat capability is a really neat feature, but in a game that already has 8 players + DM the environment in my game is already fairly chaotic especially during combat, and the extra chat output is something that I'd like to avoid if possible - plus our players enjoy making their own quips when they're hit or healed. Would it be possible to get a settings option to toggle this feature off? Erasing the preexisting messages in the options unfortunately just produces errors or has the tokens speak the numbers in chat without context.

Thanks for working on this mod, and thanks for reading.

**Comment by schlosrat** [comment]
Fixed in Version 0.3.1
