### ISSUE TITLE
Optional Token Images

### ISSUE THREAD

**Issue by apoapostolov** [schlosrat/token-health#34]
Please add an option that allows us to remove the token images from the pop up keeping its height shorter than if token images are shown. The new update UI takes too much space.

**Comment by schlosrat** [comment]
This I can do. I'll add a toggle switch that default to On, but you'll be able to switch it to Off.

I'll post again here when I've got that working.

Thanks!

**Comment by schlosrat** [comment]
This is fixed in v 0.4.1. There is now a GM configurable setting to "Enable Token Images in Dialog". The default is true (checked), but you can uncheck this and have a shorter dialog box without the token thumbnail images.
