### ISSUE TITLE
Enter Key not working on Numpad

### ISSUE THREAD

**Issue by fireman644** [schlosrat/token-health#42]
Have to use the enter key on the keyboard to access the dialog.  Numpad enter key does not work to bring up window. The enter key on the numpad works to add the damage though after I have entered it.  Is there anyway to change the options to numpad enter key?  Thanks and great job.

**Comment by schlosrat** [comment]
Token Health now uses DF Hotkeys for key bindings. This is a new change in v 0.4.0 which was necessary to ensure compatibility with Foundry 0.8.x.

You can access the specific hotkey choices by clicking on the **Hotkeys Settings** button in the **Module Settings** interface. This will bring up a dialog box that allows you to pick and choose exactly which key you'd like to use to trigger the various behaviors for Token Health. You'll only be able to assign a single key to each function, but **Numpad Enter** is an available option. Using this interface you can pretty easily customize exactly which key (and which modifiers - **Shift**, **Ctrl**, **Alt**) are used to access the four variants of the Token Health dialog.
