### ISSUE TITLE
Healing works, but damage deletes health.value

### ISSUE THREAD

**Issue by ArcShade083** [schlosrat/token-health#47]
This applies using both the damage and healing options (negative damage works fine, negative healing deletes health.value)
Currently running foundry 0.7.10
AGE system (unofficial) 0.5.1

I can install other systems to test it with if needed.

**Comment by ArcShade083** [comment]
Mm. Have discovered tokenhealth works fine with the D&D 5e module, but has this problem with the AGE module.

**Comment by schlosrat** [comment]
Sorry for the slow reply. I just tested this in Foundry V9/238 & AGE 0.10.2 (both are the latest versions) and was unable to reproduce this effect. I don't recall seeing anything like this with foundry 0.8.x and earlier versions of AGE - which is the system I routinely play. It's possible this is something particular to foundry 0.7.x and/or AGE 0.5.x.

Have you tried updating to foundry 0.8+ and newer versions of AGE?

**Comment by ArcShade083** [comment]
Also sorry for the late reply - gmail decided to bury the notification. Yes, I think it was AGE 0.5.x that was causing the problem. I updated both a few months ago, and that did resolve the issue. I'd forgotten about this ticket by the time I did the update or I'd have added a comment so you'd know to close it.
Thank you.
