### ISSUE TITLE
Settings extender causing strings to be saved as "null" instead of empty strings.

### ISSUE THREAD

**Issue by WesBelmont** [schlosrat/token-health#68]
In foundry 9 build 249 the settings extender is causing issues with empty strings and replacing them with the text null.
I deleted the contrib folder and it resolved the issues and I have not yet had any other issues. 
I assume it was used for keybinding in previous versions?

**Comment by OzBezerius** [comment]
Any news about this?

**Comment by schlosrat** [comment]
Settings extender dependency removed in 0.5.6
