### ISSUE TITLE
Mothership is weird.

### ISSUE THREAD

**Issue by ScoottyPuffJr** [schlosrat/token-health#75]
anyone play mothership with this? if not, you have like 2-3 "wounds" for a player, and each wound has its own health pool, monsters sometimes have like 6. damage will carry over to the next wound was well.  really its not even a big deal I was just working with this for a bit and just got to know if its possible haha

**Comment by schlosrat** [comment]
Token Health does understand the concept of different health pools, as well as temporary HP that are consumed first but can't be restored - a la D&D. Also spillover damage is handled when one pool is exhausted and the next is used. Perhaps the Mothership concept for wounds could be addressed that way? It sounds like it would be a feature request as presently there are only two health pools - primary and secondary. I've never played Mothership, so all I know is what you've described above, and that sounds pretty complicated with up to 6 health pools.

If you'd like to fork this project and take a stab at it you might be able to accomplish what you're looking for, but at this point, I'm mainly just maintaining this project and not adding new features. If you're successful and your fork doesn't break functionality for other games I'd be happy to help merge it into the main branch.

**Comment by ScoottyPuffJr** [comment]
Thank you so much for taking the time to reply, and explain. You have given me all the answers I'm looking for. I'm not a master at that sort of thing but It might give me an excuse to try. Have an awesome day.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
