### ISSUE TITLE
Fyi - Token Health is showing depreciated in Module Compatibility Checker

### ISSUE THREAD

**Issue by Truncated** [schlosrat/token-health#76]
Glad to see you're still kicking; love your module!

Thought you may want to update the compatibilty for token-health here: https://github.com/arcanistzed/mcc#readme
![image](https://user-images.githubusercontent.com/14208325/189034086-9fdfb298-7508-47de-83dd-1d625a5b3845.png)

**Comment by schlosrat** [comment]
Well, this is a bit puzzling. I've definitely tested TH in V10, and the compatibility is listed in the modules.json file like this:

`  "compatibility": {
    "minimum": "10",
    "verified": "10"
  }
`

I've even re-released TH with v 0.5.8 to make triple sure it's all set correctly. It seems that MCC is pulling its incorrect information from (https://docs.google.com/spreadsheets/d/14PHGJzvjhX19rzSHD7VNXtq9UZne4pUxnBn4bxvoM9k/pubhtml). I have no control over that file or its contents. If the owner of that file can't be bothered to even look at the module.json compatibility contents, then I'm not sure what can be done to fix this.

**Comment by schlosrat** [comment]
I've PM'd the owner of the spreadsheet on the Foundry Discord, updated the module entry on it's FVTT admin page, triggered multiple module update announcements in the #package-releases thread, and basically done all I can to try to make sure it's quite clear to FVTT that, in fact, this module is updated and fully compatible with V10.

It appears that the google docs spreadsheet you've linked may actually be managed manually, which is really quite puzzling when it would be so much easier to have it built via a script that scrapes the correct info from each package's module.json file. I'm sure that, given time, the spreadsheet will eventually catch up to reality wrt Token Health. There's nothing more I'm aware of that I can do at this end, so I'm closing this issue - thanks for calling it to my attention.
