### ISSUE TITLE
Version 9 Compatible Keeparound

### ISSUE THREAD

**Issue by Noggog** [schlosrat/token-health#77]
GIven that lots of modules are in flux between v9 and v10, it would be nice to have the v9 version around still to use if we need.  Lots of other modules list older versions on their foundry page, but this one only has a v10 version.   Is v9 still installable somehow?

**Comment by schlosrat** [comment]
0.5.6 is the last V9 compatible version. You can find it [here](https://github.com/schlosrat/token-health/releases/tag/0.5.6).

**Comment by Noggog** [comment]
Perfect, thanks!  Saw it on the foundry module search again.

**Comment by Noggog** [comment]
Actually, spoke to soon.  Seems to fail install when initiated through that route:
![image](https://user-images.githubusercontent.com/24981326/190875470-afbfc7bb-d9ce-45f7-b4ee-355501ed3c35.png)

**Comment by schlosrat** [comment]
Can you try a manual install using the link for the zip file? https://github.com/schlosrat/token-health/archive/refs/tags/0.5.6.zip

**Comment by Noggog** [comment]
I think it's good to go mostly.  I changed the manifest URL to:
https://raw.githubusercontent.com/schlosrat/token-health/master/module.0.5.6.json
with the `raw`, and it seemed to go down as expected.  Thanks!

**Comment by schlosrat** [comment]
Thanks for testing that! I've updated the package admin page to similarly point to the raw version. Hopefully, this will work seamlessly for others now as well.
